### ISSUE TITLE
prometeus provider

### ISSUE THREAD

**Issue by aliczin** [arkuznetsov/hirac#7]
я как инженер по инфраструктуре хочу иметь "дырку" для подключения прометея

ожидаемый конечный результат выглядит примерно так - если сходу

```
cat prometeus-server.yaml
scrape_configs:
- job_name: hirac-job
  static_configs:
  - targets: ['hirac-host:9091']
  scrape_interval: 1s
```

пока мысли такие, чтобы пробросить это дело в OScript.Web - то есть обернуть метод например отсюда https://github.com/prometheus-net/prometheus-net

в некую фигню типа

```bsl
ИмяМетрикиАнгл = "licence-count";
ИмяКонтекста="job=hirac-srv-app-01";
ИмяКонтура="instance=ones-servers";
ЗначениеМетрики=ПолучитьТекущееКоличествоЛицензииЧерезHIRAC();
КоллекцияМетокМетрики = Новый Структура(
"russian-metric-name","Количество использованных клиентских лицензий 1С"
);


АдаптерМетрикМенеджер.ОпубликоватьМетрику(
   ИмяМетрикиАнгл , ИмяКонтекста,ИмяКонтура, КоллекцияМетокМетрики, ЗначениеМетрики
);
```
