### ISSUE TITLE
Ошибки в Prometheus, кодировки, службы

### ISSUE THREAD

**Issue by iBelow** [arkuznetsov/hirac#8]
Привет
группа ошибок
расскатал hirac на англоязычной версии Win, 
1. в респонсах на запросы прилетает вместо русских имён юзеров - '??????'
2. на видне служба либо не ставится, либо ещё чего. исправил файл для создания службы, ОС кричит при старте, что служба вовремя не ответила с кодом  1053
3. если вручную запустить - в prometheus валятся ошибки 
`"expected label name, got "INVALID""`

конфа прометея
```
 - job_name: 'stat_1c'
    scrape_interval: 60s
    scrape_timeout: 20s
    params:
      format: ['prometheus']
      dim: ['_all']

    static_configs:
      - targets: ['10.0.12.110:5005']
    metrics_path: '/counter/session'
```

hirac с develop ветки, ибо с обычной других куча ошибок
